name: Deploy Images to GitHub Container Registry

on: push

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.CONTAINER_REGISTRY_TOKEN}}

      - name: "Build Image and Push to Container Registry"
        run: |
          docker build . --tag ghcr.io/${{github.repository}}:${{github.ref_name}}
          docker push ghcr.io/${{github.repository}}:${{github.ref_name}}

      - name: "Build Image and Push to Container Registry for linux/aarch64"
        run: |
          docker build . --tag ghcr.io/${{github.repository}}:${{github.ref_name}}-linux-aarch64 --platform linux/aarch64
          docker push ghcr.io/${{github.repository}}:${{github.ref_name}}-linux-aarch64

      - name: "Build Image and Push to Container Registry for linux/arm"
        run: |
          docker build . --tag ghcr.io/${{github.repository}}:${{github.ref_name}}-linux-arm --platform linux/arm
          docker push ghcr.io/${{github.repository}}:${{github.ref_name}}-linux-arm

      - name: "Tag image on main as latest"
        if: github.ref == 'refs/heads/main'
        run: |
          docker pull ghcr.io/${{github.repository}}:${{github.ref_name}}
          docker tag  ghcr.io/${{github.repository}}:${{github.ref_name}} ghcr.io/${{github.repository}}:latest
          docker push ghcr.io/${{github.repository}}:latest
